#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'rsync'
cookbook 'percona', :git => 'https://github.com/OpenSaaS/chef-percona'
cookbook 'haproxy', :git => 'https://github.com/OpenSaaS/chef-haproxy'
